improvised pipeline with more layers and feeatures !!

In [2]:
import torch
import torch.nn as nn

#model class
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()

        self.linear2 = nn.Linear(3,1) #this will get 3 inputs which will come from the prev outputs
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        linear1_out = self.linear1(features)
        relu_out = self.relu(linear1_out)
        
        linear2_out = self.linear2(relu_out)
        final_out = self.sigmoid(linear2_out)
        return final_out

In [5]:
# dataset
features = torch.rand(10,5)
print(features)

# create model
model = Model(features.shape[1])
print(model)

# call model
model(features)

tensor([[0.9171, 0.1505, 0.3159, 0.5504, 0.3238],
        [0.5723, 0.9312, 0.8434, 0.5074, 0.6268],
        [0.6963, 0.5182, 0.7708, 0.0475, 0.9923],
        [0.9893, 0.4048, 0.7674, 0.7824, 0.4743],
        [0.1055, 0.3186, 0.2549, 0.1584, 0.2533],
        [0.4234, 0.4410, 0.6292, 0.0530, 0.2814],
        [0.8329, 0.2264, 0.3570, 0.6706, 0.8709],
        [0.6028, 0.9161, 0.9284, 0.9393, 0.3319],
        [0.5330, 0.3758, 0.9016, 0.8522, 0.4932],
        [0.5674, 0.0465, 0.7634, 0.4095, 0.3268]])
Model(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


tensor([[0.3758],
        [0.3479],
        [0.3786],
        [0.3546],
        [0.3720],
        [0.3749],
        [0.3715],
        [0.3290],
        [0.3413],
        [0.3670]], grad_fn=<SigmoidBackward0>)

In [8]:
# see weights and biase
print(model.linear1.weight)
print(model.linear1.bias)
print("\n")
print(model.linear2.weight)
print(model.linear2.bias)

Parameter containing:
tensor([[-0.1389, -0.3477,  0.0321,  0.4222,  0.1166],
        [ 0.0958,  0.3713,  0.3845,  0.4368, -0.2363],
        [-0.2745,  0.0033,  0.1014,  0.2408,  0.0705]], requires_grad=True)
Parameter containing:
tensor([-0.3861, -0.3369,  0.0436], requires_grad=True)


Parameter containing:
tensor([[-0.4796, -0.1937, -0.3459]], requires_grad=True)
Parameter containing:
tensor([-0.4897], requires_grad=True)


visualize

In [9]:
# !pip install torchinfo

In [10]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00