pipeline with NN module (official way of making nn)

In [6]:
import torch
import torch.nn as nn

#model class
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [7]:
# dataset
features = torch.rand(10,5)
print(features)

# create model
model = Model(features.shape[1])
print(model)

# call model
model(features)

tensor([[0.9723, 0.1313, 0.0311, 0.9421, 0.0168],
        [0.1623, 0.5512, 0.2432, 0.7517, 0.2062],
        [0.8669, 0.2037, 0.8837, 0.4916, 0.2676],
        [0.4207, 0.9666, 0.8475, 0.2553, 0.5224],
        [0.1748, 0.3300, 0.1668, 0.0765, 0.0515],
        [0.6115, 0.9277, 0.1916, 0.3275, 0.3517],
        [0.4214, 0.9109, 0.4149, 0.2978, 0.2761],
        [0.8755, 0.9609, 0.1496, 0.9707, 0.3309],
        [0.6819, 0.3420, 0.4546, 0.5061, 0.8254],
        [0.9619, 0.4974, 0.5087, 0.0411, 0.9863]])
Model(
  (linear): Linear(in_features=5, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


tensor([[0.5045],
        [0.5474],
        [0.4643],
        [0.5613],
        [0.5657],
        [0.6059],
        [0.5883],
        [0.5773],
        [0.5220],
        [0.5550]], grad_fn=<SigmoidBackward0>)

In [8]:
# see model weights and biase
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[-0.0434,  0.3906, -0.3492, -0.2081,  0.0398]], requires_grad=True)
Parameter containing:
tensor([0.2153], requires_grad=True)


visualize

In [9]:
# !pip install torchinfo

In [10]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00