pipeline with NN module (official way of making nn)

In [21]:
import torch
import torch.nn as nn

In [22]:
#model class
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [23]:
# dataset
features = torch.rand(10,5)
print(features)

# create model
model = Model(features.shape[1])
print(model)

# call model
model(features)

tensor([[0.2632, 0.4942, 0.3894, 0.5740, 0.0456],
        [0.1321, 0.0717, 0.7542, 0.3296, 0.3200],
        [0.6213, 0.1501, 0.9898, 0.2564, 0.6621],
        [0.7653, 0.6472, 0.8924, 0.1775, 0.2559],
        [0.7949, 0.8411, 0.3955, 0.1222, 0.1014],
        [0.6534, 0.5877, 0.6343, 0.4185, 0.4550],
        [0.3593, 0.2659, 0.2789, 0.7720, 0.3372],
        [0.1129, 0.0720, 0.8789, 0.9240, 0.2439],
        [0.1254, 0.5342, 0.4650, 0.1304, 0.0932],
        [0.9930, 0.9287, 0.2730, 0.5242, 0.7974]])
Model(
  (linear): Linear(in_features=5, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


tensor([[0.6103],
        [0.5834],
        [0.6171],
        [0.6422],
        [0.6386],
        [0.6365],
        [0.6091],
        [0.6069],
        [0.5912],
        [0.6655]], grad_fn=<SigmoidBackward0>)

In [24]:
# see model weights and biase
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[0.2155, 0.2101, 0.1050, 0.1509, 0.0138]], requires_grad=True)
Parameter containing:
tensor([0.1599], requires_grad=True)


visualize

In [25]:
# !pip install torchinfo

In [26]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00