improvised pipeline with Sequential container !!

In [15]:
import torch
import torch.nn as nn

#model class
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1), #this will get 3 inputs which will come from the prev outputs
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [16]:
# dataset
features = torch.rand(10,5)
print(features)

# create model
model = Model(features.shape[1])
print(model)

# call model
model(features)

tensor([[0.7387, 0.9614, 0.1764, 0.2668, 0.7816],
        [0.4336, 0.2613, 0.3145, 0.5484, 0.2184],
        [0.7127, 0.6503, 0.8334, 0.2066, 0.9007],
        [0.1163, 0.7088, 0.5950, 0.2255, 0.2154],
        [0.5455, 0.4051, 0.8278, 0.4538, 0.6482],
        [0.3484, 0.6358, 0.6622, 0.4124, 0.2219],
        [0.3013, 0.1337, 0.9543, 0.9150, 0.2018],
        [0.8372, 0.7374, 0.9400, 0.0084, 0.6437],
        [0.7739, 0.2199, 0.6897, 0.4820, 0.9197],
        [0.3392, 0.6123, 0.6013, 0.6741, 0.3834]])
Model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)


tensor([[0.3897],
        [0.3897],
        [0.3910],
        [0.3897],
        [0.3897],
        [0.3897],
        [0.3897],
        [0.3897],
        [0.3897],
        [0.3897]], grad_fn=<SigmoidBackward0>)

In [17]:
print(model)
# see weights and biase
print(model.network[0].weight)
print(model.network[0].bias)
print("\n")
print(model.network[2].weight)
print(model.network[2].bias)

Model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)
Parameter containing:
tensor([[-0.3262,  0.1538, -0.4339,  0.3269,  0.2177],
        [-0.4274, -0.4273, -0.0825,  0.3084,  0.0361],
        [-0.2694, -0.0341,  0.3778, -0.2856,  0.4426]], requires_grad=True)
Parameter containing:
tensor([-0.3646, -0.2073, -0.4152], requires_grad=True)


Parameter containing:
tensor([[0.4932, 0.5272, 0.2172]], requires_grad=True)
Parameter containing:
tensor([-0.4488], requires_grad=True)


visualize

In [18]:
# !pip install torchinfo

In [19]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00